apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
    app: aula3
  name: nginx
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
        dc: UK
        env: Prod
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: pv-aula3
            mountPath: /usr/share/nginx/html
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: prod
        dc: UK
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pv-aula3
        persistentVolumeClaim:
          claimName: pvc-aula3
